package flowergiftshop;


import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Methmini
 */
public class SalesForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SalesForm.class.getName());
    private double selectedProductPrice = 0;
    /**
     * Creates new form SalesForm
     */
    public SalesForm() {
        initComponents();
        loadCustomers();
        loadProducts();
        
        txtQuantity.setEnabled(true);
txtQuantity.setEditable(true);
txtQuantity.setFocusable(true);

javax.swing.SwingUtilities.invokeLater(() -> {
    txtQuantity.requestFocusInWindow();
});
    }
private void loadCustomers() {
    try {
        java.sql.Connection con =
    flowergiftshop.dao.DatabaseConnection.getConnection();

        String sql = "SELECT customer_id, name FROM customers";

        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();

        cmbCustomer.removeAllItems();

        while (rs.next()) {
            cmbCustomer.addItem(
                rs.getInt("customer_id") + " - " + rs.getString("name")
            );
        }

        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
private void loadProducts() {
    try {
        java.sql.Connection con =
    flowergiftshop.dao.DatabaseConnection.getConnection();

        String sql = "SELECT product_id, product_name FROM products";

        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();

        cmbProduct.removeAllItems();

        while (rs.next()) {
            cmbProduct.addItem(
                rs.getInt("product_id") + " - " + rs.getString("product_name")
            );
        }

        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        btnSell = new java.awt.Button();
        cmbCustomer = new javax.swing.JComboBox<>();
        cmbProduct = new javax.swing.JComboBox<>();
        txtQuantity = new javax.swing.JTextField();
        txtTotalPrice = new javax.swing.JTextField();
        label5 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 228, 235));

        label1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label1.setText("Customer");

        label2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label2.setText("Product");

        label3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label3.setText("Quantity");

        label4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label4.setText("Total Price");

        btnSell.setBackground(new java.awt.Color(153, 153, 153));
        btnSell.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnSell.setLabel("SELL");
        btnSell.addActionListener(this::btnSellActionPerformed);

        cmbProduct.addActionListener(this::cmbProductActionPerformed);

        txtTotalPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantityKeyReleased(evt);
            }
        });

        label5.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 51, 153));
        label5.setText("SALES MANAGEMENT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(152, 152, 152)
                                .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(155, 155, 155)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmbCustomer, 0, 157, Short.MAX_VALUE)
                                        .addComponent(cmbProduct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(btnSell, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btnSell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed
        if (cmbCustomer.getSelectedItem() == null) {
    JOptionPane.showMessageDialog(this, "Please select a customer.");
    return;
}

if (cmbProduct.getSelectedItem() == null) {
    JOptionPane.showMessageDialog(this, "Please select a product.");
    return;
}
        try {
    int customerId = Integer.parseInt(
    cmbCustomer.getSelectedItem().toString().split(" - ")[0]
);

int productId = Integer.parseInt(
    cmbProduct.getSelectedItem().toString().split(" - ")[0]
);
    String quantityText = txtQuantity.getText().trim();

if (quantityText.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter quantity.");
    return;
}

int quantity = Integer.parseInt(quantityText);

if (quantity <= 0) {
    throw new InvalidQuantityException("Quantity must be greater than 0.");
}
java.sql.Connection stockCon =
    flowergiftshop.dao.DatabaseConnection.getConnection();

String stockSql =
    "SELECT quantity FROM products WHERE product_id=?";

java.sql.PreparedStatement stockPst =
    stockCon.prepareStatement(stockSql);

stockPst.setInt(1, productId);

java.sql.ResultSet stockRs =
    stockPst.executeQuery();

int availableStock = 0;

if (stockRs.next()) {
    availableStock = stockRs.getInt("quantity");
}

if (quantity > availableStock) {
    JOptionPane.showMessageDialog(
        this,
        "Not enough stock! Available stock: " + availableStock
    );

    stockRs.close();
    stockPst.close();
    stockCon.close();
    return;
}

stockRs.close();
stockPst.close();
stockCon.close();
   
    double totalPrice = Double.parseDouble(txtTotalPrice.getText());

    java.sql.Connection con =
    flowergiftshop.dao.DatabaseConnection.getConnection();

    String sql = "INSERT INTO sales (customer_id, product_id, quantity, total_price) VALUES (?, ?, ?, ?)";

    java.sql.PreparedStatement pst = con.prepareStatement(sql);
    pst.setInt(1, customerId);
    pst.setInt(2, productId);
    pst.setInt(3, quantity);
    pst.setDouble(4, totalPrice);

    pst.executeUpdate();
    String updateStockSql =
    "UPDATE products SET quantity = quantity - ? WHERE product_id=?";

java.sql.PreparedStatement updateStockPst =
    con.prepareStatement(updateStockSql);

updateStockPst.setInt(1, quantity);
updateStockPst.setInt(2, productId);

updateStockPst.executeUpdate();

updateStockPst.close();

    JOptionPane.showMessageDialog(this, "Sale Added Successfully!");

    con.close();
        
        } catch (InvalidQuantityException e) {
    JOptionPane.showMessageDialog(this, e.getMessage());

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
}
    }//GEN-LAST:event_btnSellActionPerformed

    private void cmbProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductActionPerformed
                                           
                                          
    try {
        String selectedProduct = cmbProduct.getSelectedItem().toString();

        int productId = Integer.parseInt(
            selectedProduct.split(" - ")[0]
        );

       java.sql.Connection con =
    flowergiftshop.dao.DatabaseConnection.getConnection();

        String sql = "SELECT price FROM products WHERE product_id=?";
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        pst.setInt(1, productId);

        java.sql.ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            selectedProductPrice = rs.getDouble("price");
            txtTotalPrice.setText(String.valueOf(selectedProductPrice)); 
        }

        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_cmbProductActionPerformed

    private void txtQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyReleased
      try {
    int quantity = Integer.parseInt(txtQuantity.getText().trim());

    double total = selectedProductPrice * quantity;

    txtTotalPrice.setText(String.valueOf(total));

} catch (NumberFormatException e) {
    txtTotalPrice.setText("");
}
    }//GEN-LAST:event_txtQuantityKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SalesForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnSell;
    private javax.swing.JComboBox<String> cmbCustomer;
    private javax.swing.JComboBox<String> cmbProduct;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables

    

   
}
